Same thing, new syntax
jeanphilippegoldman/plugin_filetools pull request #1
Opened 2018-06-06 04:44 UTC by rolandomunoz

Commit Summary:
	- Changed: field names from the dialogue box. (Now it is similar to Create Corpus...)
	- Changed: old code to new syntax

File changes:
	modified:   get_durations.praat

2018-06-06 13:20 UTC, jeanphilippegoldman commented on get_durations.praat
> +# Description: ?
put line 1

2018-06-06 13:23 UTC, jeanphilippegoldman commented on get_durations.praat
> +  sd$ = object$[fileList, ifile]
explain sd

2018-06-06 13:25 UTC, jeanphilippegoldman commented on get_durations.praat
> +fileList = Create Strings as file list: "list", folder$ + "/*" + sound_file_extension$
let keep variable names with underscore convention instead of camelCase (to distinguish from procedures), right ?

2018-06-06 13:26 UTC, jeanphilippegoldman requested changes
please review my 2 comments

2018-06-07 00:22 UTC, rolandomunoz commented on get_durations.praat
> +fileList = Create Strings as file list: "list", folder$ + "/*" + sound_file_extension$
Done!

2018-06-07 00:24 UTC, rolandomunoz commented on get_durations.praat
> +# Description: ?
Done. Now:

```
# author: jeanphilippegoldman@gmail.com
# Description: get durations of audio files in a folder
```
is this right?

2018-06-14 15:43 UTC, merged